CREATE DATABASE BancoSucos;

DROP TABLE IF EXISTS tabela_de_clientes;

CREATE TABLE tabela_de_clientes (
  CPF VARCHAR(11) PRIMARY KEY,
  NOME VARCHAR(100),
  ENDERECO_1 VARCHAR(150),
  ENDERECO_2 VARCHAR(150),
  BAIRRO VARCHAR(50),
  CIDADE VARCHAR(50),
  ESTADO VARCHAR(2),
  CEP VARCHAR(8),
  DATA_DE_NASCIMENTO DATE,
  IDADE SMALLINT,
  SEXO VARCHAR(1),
  LIMITE_DE_CREDITO FLOAT,
  VOLUME_DE_COMPRA FLOAT,
  PRIMEIRA_COMPRA BOOLEAN,
  total_pedidos_realizados INT
);

DROP TABLE IF EXISTS tabela_de_vendedores;

CREATE TABLE tabela_de_vendedores (
  MATRICULA VARCHAR(5) PRIMARY KEY,
  NOME VARCHAR(100),
  PERCENTUAL_COMISSAO FLOAT,
  DATA_ADMISSAO DATE,
  DE_FERIAS BOOLEAN,
  BAIRRO VARCHAR(50)
);

DROP TABLE IF EXISTS notas_fiscais;

CREATE TABLE notas_fiscais (
  NUMERO SERIAL PRIMARY KEY,
  CPF VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR(5) NOT NULL,
  DATA_VENDA DATE,
  IMPOSTO FLOAT,
  FOREIGN KEY (MATRICULA) REFERENCES tabela_de_vendedores (MATRICULA),
  FOREIGN KEY (CPF) REFERENCES tabela_de_clientes (CPF)
);

DROP TABLE IF EXISTS tabela_de_produtos;

CREATE TABLE tabela_de_produtos (
  CODIGO_DO_PRODUTO VARCHAR(10) PRIMARY KEY,
  NOME_DO_PRODUTO VARCHAR(50),
  EMBALAGEM VARCHAR(20),
  TAMANHO VARCHAR(10),
  SABOR VARCHAR(20),
  PRECO_DE_LISTA FLOAT
);

DROP TABLE IF EXISTS itens_notas_fiscais;

CREATE TABLE itens_notas_fiscais (
  NUMERO INT,
  CODIGO_DO_PRODUTO VARCHAR(10),
  QUANTIDADE INT,
  PRECO FLOAT,
  PRIMARY KEY (NUMERO, CODIGO_DO_PRODUTO),
  FOREIGN KEY (CODIGO_DO_PRODUTO) REFERENCES tabela_de_produtos (CODIGO_DO_PRODUTO),
  FOREIGN KEY (NUMERO) REFERENCES notas_fiscais (NUMERO)
);